name: GoImages Backend CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          cd ./goimages-backend
          npm ci

      - name: Setup environment
        run: |
          touch .env
          echo "${{ secrets.PROD_BACKEND_ENV_FILE }}" > .env

      - name: Deploy Application
        run: |
          cd ./goimages-backend
          sudo pm2 restart goimages-backend-service
